### PR TITLE
Fix Undefined method `key?' for nil:NilClass error.

### LINKED ISSUE #670: Rule#each. Undefined method `key?' for nil:NilClass
**Describe the bug**

After calling contract with nested hash when the root key is nil and rule with `.each` applied the error occurs
```
NoMethodError:
   undefined method `key?' for nil:NilClass
```
**To Reproduce**
Giving a simple contract like this one:

```
class Index < Dry::Validation::Contract
  params do
    optional(:filter).hash do
      optional(:user_ids).array(:integer)
    end
   end

  rule(filter: :user_ids).each do
    key.failure('Not found') unless User.exists?(value)
  end
end

Index.new.call(filter: nil)
```
**Expected behavior**

**Expected behavior**
The contract does not raise any errors.

**Your environment**
- dry-validation 1.5.6
- Ruby 2.6.5

### PR DESCRIPTION
**Pull request by alexxty7**
Fixes #670

### CODE REVIEW

File: lib/dry/validation/values.rb [hunk 1]
```diff
@@ -70,6 +70,8 @@ def key?(key, hash = data)
             return result
           elsif e.is_a?(Symbol) && a.is_a?(Array)
             return false
+          elsif a.is_a?(String) || a.nil?
+            return false
```
Comment (solnic) [inline lib/dry/validation/values.rb:74]: Why `a.is_a?(String)` was needed? It shouldn't be, at this point all keys should be symbolized.

**Review by solnic — CHANGES_REQUESTED** [review]
Thanks for addressing this! I need to clarify one thing before this can be merged, please see my question in the review.

File: lib/dry/validation/values.rb (hunk 1 above)
Comment (alexxty7) [reply lib/dry/validation/values.rb:74]: It for the case when root value is a string. I have checked and it is not symbolized.
It covered by this test case
```
  let(:data) do
    {
      name: "Jane",
      address: {city: "Paris", geo: {lat: 1, lon: 2}},
      phones: [123, 431],
      billing_address: nil,
      card: ""
    }
  end

    it "returns false when a nested key is not present and root key is string" do
      expect(values.key?([:card, :not_here])).to be(false)
    end

```

Comment (alexxty7) [reply lib/dry/validation/values.rb:74]: Maybe I should check for valid types instead?

```
          elsif !(a.is_a?(Array) || a.is_a?(Hash))
            return false
```

Comment (solnic) [reply lib/dry/validation/values.rb:74]: @alexxty7 aahh that's right, this can happen! I think it should be handled separately though, so:

```ruby
# ...
elsif a.nil?
  return false
elsif a.is_a?(String)
  return false
# ...
end
```

Comment (alexxty7) [reply lib/dry/validation/values.rb:76]: @solnic updated

**Review by solnic — APPROVED** [review]
Thank you!

**Comment by TimoMoss** [comment]
hello, 
I  have a similar problem when I use a rule for each element of an array. 
dry-validation  '~> 1.4'

```
ValidateParams < Dry::Validation::Contract
    schema do
        required(:data).hash do
          required(:attributes).hash do
            required(:items).array(:string)
         end
       end
    end

    rule(%i[data attributes items]).each do
       message = 'invalid numeric string'
       key(keys.flatten).failure(message) if value&.!~ /^(\d)+$/
    end
 end
```

```
RSpec.describe ValidateParams do
  let(:validation) { described_class.new }

  let(:params) do
    {
        data: {
            attributes: {
               items: ['123', '123', '123']
            }
        }
    }
  end

  it 'looks like failure' do
    expect(validation.call(params)).to be_failure
  end
end
```
result 
```
>>  Failure/Error: expect(validation.call(params)).to be_failure
     NoMethodError:
       undefined method `key?' for nil:NilClass
```

at the moment I have it solved by:

      ```
      rule(%i[data attributes items]) do
         value.each_with_index do |v, i|
           message = 'invalid numeric string'
           key(keys.flatten << i).failure(message) if v&.!~ /^(\d)+$/
        end
      end
```
But it's definitely a trick.
I'd highly appreciate it if anybody explains how can I make it work without such tricks.   
Many thanks in advance
